name: Test
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare cache
        run: |
          curl https://api.cloudflare.com/client/v4/zones/$ZONE_ID/purge_cache \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer $CLOUDFLARE_API_TOKEN' \
          -d '{"hosts": ["twotech.twohoursonelife.com"]}'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ZONE_ID: ${{ vars.ZONE_ID }}
